spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Customer?serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always  
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
        
security:
  oauth2:
     resource:
        token-info-uri: http://localhost:9090/oauth/check_token
     client:      
        client-id: mobile
        client-secret: pin    
 
mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: dayoanifannu@gmail.com
    password: dayoanu34
    port: 465
    properties:
      mail:
        smtp:
          port: 25
          auth: true
          starttls:
              enable: true
          socketFactory:
            port: 587
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    protocol: smtp
    test-connection: false
   
